[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "an_kohyasetupmanager"
version = "0.1.6"
description = "A package for an_kohyasetupmanager."
authors = [
    { name = "Atsushi888", email = "vtgrotxu@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = ['an_DebugHelper', 'an_EnvManager', 'an_CudaUtility']

[project.urls]
Homepage = "https://github.com/Atsushi888/an_kohyasetupmanager"
Repository = "https://github.com/Atsushi888/an_kohyasetupmanager"
