[project]
name = "reference-mcp"
version = "0.1.0"
description = "Get citation data from CiteAs and Google Scholar"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["git", "mcp", "llm", "automation"]
license = {text = "MIT"}
dependencies = [
    "mcp==1.4.1",
    "scholarly==1.7.11",
]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
reference-mcp = "reference_mcp.server:main"

[project.urls]
Homepage = "https://github.com/ndchikin/reference-mcp"
Repository = "https://github.com/ndchikin/reference-mcp"
Issues = "https://github.com/ndchikin/reference-mcp/issues"
