[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dspackage"
version = "0.1.5"
authors = [{name = "Anar", email = "anarstanislavlavrenov@gmail.com"}]
description = "DSpackage: A Data Science Toolkit"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "torch", "torchtext"
]
license = {text = "MIT"}
[tool.setuptools]
license-files = []
