[project]
name = "dap-types"
version = "20250315!1.69.post1"
description = "Debugger Adapter Protocol types for Python."
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.28.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"