[project]
name = "Transcriber"
version = "0.1.3"
description = "A simple tool to transcribe audio files"
readme = "README.md"
authors = [
    { name = "NourEldin", email = "noureldin.osama.saad@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "faster-whisper>=1.1.1",
    "openai-whisper>=20240930",
    "pydantic-settings>=2.7.1",
    "python-docx>=1.1.2",
    "rich>=13.9.4",
    "stable-ts>=2.18.3",
    "yt-dlp==2025.1.15",
]

[project.scripts]
transcribe = "Transcriber.transcriber:transcribe"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "Transcriber"
