[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "splinaltap"
version = "0.8.0"
description = "Keyframe interpolation and expression evaluation that goes to eleven!"
readme = "splinaltap/README.md"
authors = [
    {name = "Chris", email = "no-reply@example.com"}
]
license = {file = "splinaltap/LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/chrisdreid/splinaltap"
"Bug Tracker" = "https://github.com/chrisdreid/splinaltap/issues"

[project.optional-dependencies]
numpy = ["numpy>=1.20.0"]
visualize = ["matplotlib>=3.5.0", "numpy>=1.20.0"]
gpu = ["jax>=0.3.0", "jaxlib>=0.3.0", "cupy>=10.0.0"]
numba = ["numba>=0.55.0", "numpy>=1.20.0"]
all = ["numpy>=1.20.0", "matplotlib>=3.5.0", "jax>=0.3.0", "jaxlib>=0.3.0", "cupy>=10.0.0", "numba>=0.55.0"]

[project.scripts]
splinaltap = "splinaltap.cli:main"