[project]
name = "ad_bs_converter"
version = "1.2.1"
description = "A Python package to convert AD dates to BS dates."
readme = "README.md"
authors = [
    { name = "Aayush Dip Giri", email = "giridip862101@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.6",
    "setuptools>=76.0.0",
    "twine>=6.1.0",
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
keywords = ["date-converter", "ad-to-bs", "nepali-date"]

[project.urls]
"Bug Tracker" = "https://github.com/your-username/ad_bs_converter/issues"
"Documentation" = "https://github.com/your-username/ad_bs_converter#readme"
"Source Code" = "https://github.com/your-username/ad_bs_converter"

[project.scripts]
ad_bs_converter = "ad_bs_converter:main"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
