[project]
name = "pystools"
version = "0.0.88"
authors = [
  { name="木坦坦", email="devzhao@126.com" },
]
description = "pystools"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
#    "requests>=2.25.1",
#    "numpy>=1.0.0",
    "requests-toolbelt",
    "loguru",
#    "pika==1.3.1",
    "pika",
    "cos-python-sdk-v5",
    "oss2",
    "urllib3",
    "shortuuid",
    "webdriver-manager>=4.0.0",
    "selenium>=4.10.0",
    "python-dateutil",
    "pytz",
#    "Pillow-SIMD"

]


[project.urls]
"Homepage" = "https://github.com/devzhaohan/HMTools"
"Bug Tracker" = "https://github.com/devzhaohan/HMTools/issues"
