[project]
name = "flightpath"
version = "0.2.2"
description = "A command-line tool for analyzing critical paths in Apache Airflow DAGs."
authors = [
    {name = "Andrew Hannigan", email = "andrew.s.hannigan@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.7",
    "requests>=2.32.3",
    "duckdb>=1.1.1",
    "apache-airflow-client>=2.10.0",
]

[project.scripts]
flightpath = "flightpath.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["flightpath"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
