[build-system]
requires = ["setuptools", "wheel", "Cython<3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gtk-llm-chat"
version = "1.3.1"
description = "Una interfaz grÃ¡fica GTK para chatear con modelos de lenguaje (LLMs)"
readme = "README.md"
authors = [{ name = "Sebastian Silva", email = "sebastian@fuentelibre.org" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
keywords = ["gtk", "chat", "llm", "ai"]
dependencies = [
    "PyGObject>=3.42.0",
    "markdown-it-py"
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/icarito/gtk_llm_chat"
Issues = "https://github.com/icarito/gtk_llm_chat/issues"
Repository = "https://github.com/icarito/gtk_llm_chat.git"

[project.scripts]
gtk-llm-chat = "gtk_llm_chat.main:main"
gtk-llm-applet = "gtk_llm_chat.gtk_llm_applet:main"

[tool.setuptools.packages.find]
exclude = ["desktop*"]

[tool.setuptools.data-files]
"share/applications" = ["desktop/gtk-llm-chat.desktop", "desktop/gtk-llm-applet.desktop"]