[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server-kubernetes"
version = "0.1.3"
description = "A Python MCP server for Kubernetes environments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
mcp-server-kubernetes = "mcpKubernetes:main"

