[build-system]
requires = ["setuptools","argcomplete", "GitPython", "prompt_toolkit"]
build-backend = "setuptools.build_meta"
[project]
name = "copy-to"
version = "1.4.9"
authors = [
  { name="Excited Bore", email="brunt-curry-wobble@duck.com" },
]

keywords = ["copy-to", "setuptools", "development"]
description = "A little commandline tool to copy and paste multiple files and directories to single directory with use of configuration"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [ "argcomplete >= 3.2.1" , "GitPython >= 3.1.14", "prompt_toolkit >= 3.0.20" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
copy-to = "copy_to:main"

[project.urls]
"Homepage" = "https://github.com/excited-bore/copy-to"
"Bug Tracker" = "https://github.com/excited-bore/copy-to/issues"
