[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "metalogger"
version = "1.0.0"
authors = [
  { name = "Welk", email = "advusdt@gmail.com" },
]
description = "Асинхронный логгер с ротацией файлов и цветным выводом"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "aiofiles >= 24.1.0",
]

[project.urls]
"Homepage" = "https://github.com/welkmeta/metalogger"