[project]
name = "zkeymap"
version = "0.1.5"
description = "ZMK Keymap Generator"
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers"
]

license = "MIT"
license-files = ["LICEN[CS]E*"]

authors = [
    { name = "Frank Martinez", email = "mnesarco@gmail.com" }
]

requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
indent-width = 4

[project.urls]
Homepage = "https://github.com/mnesarco/zkeymap"
Issues = "https://github.com/mnesarco/zkeymap/issues"

[project.optional-dependencies]
drawer = [
    "keymap-drawer>=0.21.0"
]