[project]
name = "arraypartition"
version = "1.1.0"
description = "Container module for ArrayLike Partition class behaviour"
authors = [
    {name = "Daniel Westwood",email = "daniel.westwood@stfc.ac.uk"}
]
license = {text = "BSD 3"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dask>=2024",
    "numpy (<=2.0.2)",
    "netcdf4 (>=1.7.2,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "7.1.2"