[project]
name = "exploit-sensei"
version = "0.1.6"
description = "LLM-powered exploitation recommendation tool"
readme = "README.md"
authors = [
    { name = "hdks", email = "hdks.bug@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "openai>=1.66.3",
    "rich>=13.9.4",
    "ruff>=0.10.0",
]

[project.urls]
Homepage = "https://github.com/hideckies/exploit-sensei"
Documentation = "https://github.com/hideckies/exploit-sensei"
Repository = "https://github.com/hideckies/exploit-sensei.git"
Issues = "https://github.com/hideckies/exploit-sensei/issues"

[project.scripts]
exploit-sensei = "exploit_sensei:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
