[project]
name = "gradiochat"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hopsakee", email = "jdejong@posteo.nl" }
]
requires-python = ">=3.10"
dependencies = [
    "fastcore>=1.7.29",
    "gradio>=5.20.1",
    "openai>=1.65.4",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "together>=1.4.6",
]

[project.scripts]
gradiochat = "gradiochat:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "nbdev>=2.3.34",
]
