[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "Group1402122"
version = "0.2.7"
description = "A test package for learning!"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Anton", email = "s235256@dtu.dk"}]
dependencies = ["numpy>=2.0.2, <3.0", "pandas>=2.2.3,<3.0", "anndata>=0.11,<1.0", "scanpy>=1.9.8,<2.0"]  # Add dependices here e.g ["numpy", "requests"] 


