[project]
name = "semantic-fera"
version = "0.0.2"
dependencies = [
    "semantic-api >= 0.0.18",
    "behave == 1.2.6",
    "paho-mqtt == 2.1.0",
    "pydantic == 2.10.4",
    "pydantic_core == 2.27.2",
    "PyMonad == 2.4.0",
    "pyrsistent == 0.20.0",
    "future == 0.18.2",
    "typing == 3.7.4.3",
    "typing_extensions == 4.12.2",
    "urllib3 == 1.26.5"
]
authors = [
  { name="William A Coolidge", email="wac@mmmi.sdu.dk" },
]
description = "FERA ontologies, type definitions, type constructors, configurations "
dynamic = ["readme"]

[build-system]
requires = ["hatchling",  "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# replace relative links with absolute links
pattern = '\[(.+?)\]\(((?!https?://)\S+?)\)'
replacement = '[\1](https://source.coderefinery.org/fera/semantic-fera/-/blob/main/\g<2>)'

requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text="Apache Licenses 2.0"}
license-files = ["LICEN[CS]E*"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]

[tool.hatch.build.targets.wheel.sources]
"src/semantic" = "semantic"

[tool.hatch.build.targets.sdist]
# Basically everything except hidden files/directories (such as .github, .devcontainers, .python-version, etc)
include = [
  "/*.toml",
  "/*.json",
  "/*.lock",
  "/*.md",
  "/*.svg",
  "/mypy.ini",
  "/noxfile.py",
  "bin/*",
  "examples/*",
  "src/*",
  "tests/*"
]

[project.urls]
Homepage = "https://source.coderefinery.org:fera/semantic-fera"
Issues = "https://source.coderefinery.org:fera/semantic-fera/-/issues"

[tool.behave]
stderr_capture=false
stdout_capture=false
log_capture=false
paths=["tests"]


    
