[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "db-connections"
version = "1.0"
description = "Módulo para gerenciamento de conexões com bancos de dados"
readme = "README.md"
authors = [
    {name = "Bruno Sardou", email = "bruno.sardou@outlook.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=1.0.0",
    "sqlalchemy>=1.4.0",
    "pyodbc>=4.0.30",
    "python-dotenv>=0.15.0"
]
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://github.com/bruno-sardou/quick-db-connection"