[project]
name = "dnms-task"
version = "0.1.5"
description = "Delayed Non-Match-To-Sample task for IBLRIG"
authors = [
    { name = "Tatiana Dupak (University of Bordeaux)", email = "tatiana.dupak@u-bordeaux.fr" },
]
keywords = [
    "IBL",
    "neuro-science",
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.entry-points."iblrig.plugins"]
task_dnms = "task:Session"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.package]
include = [
    "dnms_task/**/*",
]
