[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "payselection"
version = "1.0.1"
description = "Payselection SDK allows you to integrate work with payments for applications"
readme = "README.md"
authors = [
    { name = "Rudenkov Vadim", email = "vadzim.r@gofarsoft.org" }
]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/Payselection/Payselection-PayApp-SDK-Python"
Issues = "https://github.com/Payselection/Payselection-PayApp-SDK-Python/issues"
