[project]
name = "translation_hub"
version = "0.11.7"
description = "没有任何依赖的翻译库，API 统一简单易用，适合快速集成翻译功能而不想引入庞大的依赖库"
authors = [
    { name = "PythonImporter", email = "271374667@qq.com" }
]
dependencies = [
    "requests>=2.32.3",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.urls]
"Homepage" = "https://github.com/271374667/translation_hub"
"Source Code" = "https://github.com/271374667/translation_hub"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["translation_hub"]

[tool.hatch.build]
include = [
    "translation_hub/**/*",
]
