[tool.poetry]
name = "repli"
version = "0.2.0"
description = "Read–Eval–Print Loop Interpreter"
authors = ["luojiahai <ljiahai@hotmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
example = "example:main"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.9.4"
pytest = "^8.3.5"
pytest-mock = "^3.14.0"
flake8 = "^7.1.2"
black = "^25.1.0"
isort = "^6.0.1"
coverage = "^7.6.12"

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
