
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev92"
name = "GitTidy"
requires-python = ">=3.10"
dependencies = [
    "LoggerMan == 0.0.0.dev94",
    "PyShellMan == 0.0.0.dev53",
    "MDit == 0.0.0.dev63",
    "ExceptionMan == 0.0.0.dev63",
]
