[project]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tryXinput"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
pyglet = ">=2.1.3, <3"
ipykernel = ">=6.29.5, <7"
pip = ">=25.0.1, <26"
build = ">=1.2.2.post1, <2"
twine = ">=6.1.0, <7"
pyxel = ">=2.3.16, <3"
